language: node_js
node_js:
  - "9"
  - "4"
  - "6"
  - "8"
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install php5-cli
  - sudo apt-get install parallel
services:
  - docker
