sudo: false
language: node_js
branches:
  only:
    - master
    - development
    - travis
node_js:
   - "4.0.0"
   - "0.12"
   - "0.12.0"
   - "0.11"
   - "0.10"
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
