#!/bin/bash

SCRIPT_PATH="$(dirname "$0")/../lib/binaries/CLI.js"

# Check if 'bun' is available, otherwise use 'node'
if command -v bun &> /dev/null
then
    bun "$SCRIPT_PATH" "$@"
else
    node "$SCRIPT_PATH" "$@"
fi
